=== mizunoto/BrainDiver/chunk.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "priority": {
            "type": "number",
            "minimum": -1,
            "maximum": 100
        },
        "genre": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "include": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "params": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "access_level": {
                        "type": "number",
                        "minimum": -1,
                        "maximum": 10
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "document",
                            "description",
                            "flavor",
                            "judge",
                            "system",
                            "enemy",
                            "archetype",
                            "glossary",
                            "section",
                            "item",
                            "consumable",
                            "data_core",
                            "guideline",
                            "ignore",
                            "scenario"
                        ]
                    }
                }
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [
        "name",
        "priority",
        "genre",
        "params"
    ]
}

=== mizunoto/BrainDiver/chunk/glossary/automata.json
{
    "name": "オートマタ",
    "priority": 0,
    "genre": [
        "glossary",
        "enemy",
        "automata"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "flavor",
            "value": "リーサル・クラックを境に散見されるようになった自律行動機械。安易に対峙するのは危険だが、そのパーツには遺失技術が使われている痕跡があり、無力化すればいい値段で売れる可能性がある。獣型や人型など用途によって様々な形状の物が存在する。"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/glossary/strayer.json
{
    "name": "ストレイヤー",
    "priority": 0,
    "genre": [
        "glossary",
        "player",
        "strayer"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "報酬次第でどんな依頼でも受ける何でも屋。輪転街が通る跡をサンクタム間の道に例え、その道を外れて行動をするため、「寄り道する者」という言葉が由来として定着した。"
        },
        {
            "access_level": 0,
            "type": "description",
            "value": "輪転街に所属する義務などはなく、単に輪転街の方が割のいい仕事が集まるからという理由で輪転街と行動を共にしているものが多い。依頼の内容次第では同じストレイヤーでも利害の対立関係に陥り、最悪の場合敵対することもある。"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/rules/canpain/market/market_price.json
{
    "name": "相場判定",
    "priority": 0,
    "genre": [
        "market",
        "price",
        "judge",
        "LUK"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "セッション間に一度だけデータ・コアの販売価格の相場判定を行うことができます。LUKによって判定を行い、販売価格に出目(%)上乗せされます。これは次のセッション開始まで固定されます。"
        },
        {
            "access_level": 0,
            "type": "judge",
            "status": "LUK",
            "skill": "使用不可",
            "adjust": "なし",
            "value": "相場判定"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/section/introduction.json
{
    "name": "初めに",
    "priority": 0,
    "genre": [
        "section",
        "description"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "生成AIがGMを務めることを前提に設計された、新時代のTRPG「隔絶輪廻のブレインダイバー」は、プレイヤーとGM（ゲームマスター）が協力して物語を紡ぐテーブルトーク・ロールプレイングゲームです。プレイヤーは、退廃的なSF世界で様々な任務に挑み、自分の選択で物語を動かしていきます。"
        },
        {
            "access_level": 8,
            "type": "document",
            "value": "このガイドラインは、TRPG「隔絶輪廻のブレインダイバー」のシナリオを作成するすべてのクリエイターを対象としています。一貫性のあるゲーム体験を提供し、プレイヤーがこの世界の物語に没頭できるシナリオの作成を支援することを目的としています。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/compiler/item_drop.json
{
    "name": "",
    "priority": 0,
    "genre": [],
    "include": [
        "mob_drop",
        "boss_drop"
    ],
    "params": [
        {
            "access_level": 8,
            "type": "document",
            "value": "敵を倒した際のドロップアイテムは、プレイヤーのモチベーションとゲーム経済に直接影響します。以下の目安を参考に、敵の種類やシナリオの難易度に応じた報酬を設定してください。これはシナリオ全体の報酬とは別に、戦闘の勝利で直接得られるアイテムを想定しています。"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/glossary/synthesis.json
{
    "name": "シンセシス",
    "priority": 0,
    "genre": [
        "glossary",
        "enemy",
        "synthesis"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "人類によく似た姿の存在。一体一体の強さは大したことはないが、その能力は集団で真価を発揮し、まるで全員が一つの生物かのように緻密な連携で翻弄してくる。"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/glossary/rotary_city.json
{
    "name": "輪転街",
    "priority": 0,
    "genre": [
        "glossary",
        "location",
        "rotary_city"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "flavor",
            "value": "サンクタム間を移動し、物資や情報の交換を担う移動都市の総称。複数存在しているが、サンクタム間を移動し続けるという性質上、輪転街同士が遭遇することは滅多になく、サンクタムのように自らの街に独自の呼称を付けている輪転街は少ない。物資や情報の運び屋としての役割の他、遺跡の探索やオートマタ駆除をはじめとする治安の維持を担う側面もあり、プレイヤーたちストレイヤーが主にこういった危険のある依頼を遂行している。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/rules/system/judge/judge_rule.json
{
    "name": "判定の基本ルール",
    "priority": 10,
    "genre": [
        "system",
        "rule",
        "judge"
    ],
    "params": [
        {
            "access_level": 0,
            "type": "system",
            "value": {
                "name": "判定方法",
                "description": "プレイヤーの判定、対抗判定は1D100で行います。ダイスの出目が目標値以下で成功判定です。"
            }
        },
        {
            "access_level": 0,
            "type": "system",
            "value": {
                "name": "目標値の計算式",
                "description": "目標値は「基礎ステータス1種 + 関連スキルレベル1種 + アイテムなどによる補正値」により算出されます。"
            }
        },
        {
            "access_level": 0,
            "type": "system",
            "value": {
                "name": "クリティカル",
                "description": "出目が1～5だった場合、無条件で大成功となり、通常より大きな結果を得られます。"
            }
        },
        {
            "access_level": 0,
            "type": "system",
            "value": {
                "name": "ファンブル",
                "description": "出目が96～100だった場合、無条件で大失敗となり、予期せぬ悪い結果をもたらします。"
            }
        }
    ]
}
