=== mizunoto/BrainDiver/chunk.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "priority": {
            "type": "number",
            "minimum": -1,
            "maximum": 100
        },
        "genre": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "include": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "params": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "access_level": {
                        "type": "number",
                        "minimum": -1,
                        "maximum": 10
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "document",
                            "description",
                            "flavor",
                            "judge",
                            "system",
                            "enemy",
                            "archetype",
                            "glossary",
                            "section",
                            "item",
                            "consumable",
                            "data_core",
                            "guideline",
                            "ignore",
                            "scenario"
                        ]
                    }
                }
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [
        "name",
        "priority",
        "genre",
        "params"
    ]
}

=== mizunoto/BrainDiver/chunk/rules/system/hacking/mind_jack.json
{
    "name": "マインド・ジャック",
    "priority": 0,
    "genre": [
        "system",
        "hacking"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "ハッキングに成功したときにハッキングされた対象の処理負荷が最大のときに発生する状態異常です。発生すると対象は2ターン行動不能になります。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/rules/canpain/session/session_estimate.json
{
    "name": "セッション評価",
    "priority": 0,
    "genre": [
        "session",
        "estimate"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "シナリオが完了し、GMがシナリオの評価基準に基づき報酬を付与するフェーズです。"
        },
        {
            "access_level": 8,
            "type": "document",
            "value": "ミッションの結果を評価し、報酬を付与します。"
        },
        {
            "access_level": 8,
            "type": "document",
            "value": "成功度合いに応じて報酬を変動させましょう。（例：目標達成＋αの成果があれば追加報酬）"
        },
        {
            "access_level": 8,
            "type": "document",
            "value": "次のシナリオに繋がる伏線や、新たな謎を提示するのも良いでしょう。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/rules/canpain/return_to_base.json
{
    "name": "輪転街への帰還",
    "priority": 0,
    "genre": [
        "system",
        "rules"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "キャンペーン中にHPが0になった場合、キャラクターは一時的に意識を失い、戦闘中であれば戦闘から離脱します。プレイヤーが全員行動不能になった場合、進行中のセッションはそこで終了し、失敗扱いとなります。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/compiler/difficulty_design.json
{
    "name": "難易度と敵の設計指針",
    "priority": 0,
    "genre": [
    ],
    "include": [
        "player_level",
        "additional_arms",
        "enemy_status",
        "drop_item",
        "judge_difficulty"
    ],
    "params": [
        {
            "access_level": 8,
            "type": "document",
            "value": "ゲームバランスを保つため、以下の数値を基準に敵データや判定の目標値を設定してください。"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/item/consumable/high_density_gel.json
{
    "name": "高密度エネルギーゲル",
    "priority": 0,
    "genre": [
        "item",
        "consumable",
        "energy",
        "buy",
        "use"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "戦闘用に開発された高効率のエネルギーを纏めたゲル。効果は高いが一時的に行動を阻害するのが難点。"
        },
        {
            "access_level": 0,
            "type": "item",
            "use": {
                "effect": {
                    "energy": 100,
                    "special": "次のターンに行動妨害状態になる"
                }
            },
            "worth": 80,
            "value": "高密度エネルギーゲル"
        }
    ]
}

=== mizunoto/BrainDiver/chunk/rules/canpain/character_lost.json
{
    "name": "キャラクターロスト",
    "priority": 0,
    "genre": [
        "system",
        "rules",
        "description"
    ],
    "include": [],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "HPが0になった場合、キャラクターは命を落とし、完全にゲームから退場します。再度プレイする場合は新たにキャラクタークリエイトから行う必要があります。生成AIをGM役にしている場合、前キャンペーンのキャッシュが残っていて混同する可能性があるので枠を立て直すことをお勧めします。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/rules/canpain/market/market.json
{
    "name": "マーケットの利用",
    "priority": 0,
    "genre": [
        "market",
        "system",
        "rules"
    ],
    "include": [
        "skill_earn",
        "buy_equip",
        "buy_item",
        "negotiate_discount",
        "sell_equip",
        "sell_item",
        "sell_data_core"
    ],
    "params": [
        {
            "access_level": 0,
            "type": "description",
            "value": "共通通貨ℂを消費して利用できるマーケットです。セッション間の準備期間に利用することができます。"
        }
    ]
}

=== mizunoto/BrainDiver/chunks/item/consumable/consumale.json
{
    "name": "消費アイテム",
    "priority": 0,
    "genre": [
        "consumable",
        "item"
    ],
    "include": [
        "data_core",
        "hp_healing_item",
        "energy_healing_item"
    ],
    "params": [
        {
            "access_level": 0,
            "type": "section",
            "value": "消費アイテムの一覧です"
        }
    ]
}
